### ISSUE TITLE
Why it is root needed? 

### ISSUE THREAD

**Issue by ilie321** [AndroidAudioMods/ViPER4Android#18]
It is not possible to make app with no root? Thank you

**Comment by seffparker** [comment]
The Viper4Android module works by custom adding audio processing libraries in to Android system, that eventually requires root privileges. Unless the these libraries are pre-included in the ROM, or there is a way to side-load user libraries (which probably not going to happen due to securities enforced in Android by Google)

**Comment by ilie321** [comment]
Thank you for the explanation
