### ISSUE TITLE
Driver not detected on v3.0

### ISSUE THREAD

**Issue by SCrid2000** [AndroidAudioMods/ViPER4Android#25]
Pixel 6a running the February update. 
Was working with 1.0. Occasionally worked with 2.0, but would crash.
Installed 3.0 both as an update, and then tried again after uninstalling both the driver and the app.
With v3, I am getting a "driver not detected" error. 
Happy to provide any additional information to help diagnose.

**Comment by iscle** [comment]
Hey! Thanks for the feedback :)

Strange, I'm guessing your device is 64-bit only? (I'm not sure about this, but if in AIDA64/CPU -> Instruction Set is 64 bit ARMv9-A, it is).

Ping me on Telegram so that we can run a couple of commands to try and see what's happening.

In the meanwhile, you can use the v0.3.0 app and keep the v0.1.0 driver.

**Comment by SCrid2000** [comment]
Update: not an issue with viper, it was caused by https://github.com/topjohnwu/Magisk/issues/6688
