### ISSUE TITLE
Driver version 0.2.0 works for a short period of time and then crashes

### ISSUE THREAD

**Issue by VadymSavchenko** [AndroidAudioMods/ViPER4Android#8]
> Device: Google Pixel 7 Pro
> Android 13
> Build number: TD1A.220804.009.A2
> Headphones: AirPods Pro 1st Gen

Previous version 0.1.0 only worked in legacy mode. Same with 0.2.0, but now, right after switching the legacy mode on, the driver would work for around 30 seconds to 1 minute, and then it crashes.

Not sure if there are log files, but if there are, let me know where to find them.

**Comment by ekeppel** [comment]
Similar issue here.  Just updated from 0.1.0 to 0.2.0, and now the driver crashes shortly after enabling the Field Surround effect. Toggling Viper bass also intermittently crashed the driver, but Field Surround crashes it every time.

Pixel 7 on Jan 2023 update.

**Comment by Iscle** [comment]
Hey, thanks for the feedback. It is due to the SoftwareLimiter (threshold limit) feature. It can't be disabled. If you're having issues, switch back to the 0.1.0 driver (magisk module). You can keep using the 0.2.0 app (apk), it is backwards compatible.

**Comment by ekeppel** [comment]
Thanks, that got me up and running again for the time being.  Btw, we all really appreciate the effort you're making on this project.  It's so nice to have V4A again after being without it since switching to the P7.  Is there a public thread on XDA that I'm missing?  A cursory search didn't turn up anything, but I think this project would get a lot of attention if more people were aware of it.

**Comment by Iscle** [comment]
No XDA thread for now, until it's out of alpha phase.

**Comment by 7tattoo** [comment]
The Same bug haved on SΛMSUNG Galaxy S22 Ultra.

**Comment by Iscle** [comment]
Hi! The issue has been fixed! Reopen the issue if you find it still happens!
