### ISSUE TITLE
Blanked out options

### ISSUE THREAD

**Issue by 0izayoi0** [AndroidAudioMods/ViPER4Android#95]
I would like to run V4A on my Nothing Phone 2 but i lose features when i switch to this reverse engineered version. the old version wont even launch, saying there are "no drivers" and stuck at NaN% 0/0

**Comment by vjburic1** [comment]
32-bit libs unsupported very likely, which is causing Repackaged install to get stuck, that NaN% error.

Run this in Terminal:

su
dumpsys media.audio_flinger | grep -E 'lib|lib64' | awk -F '/' 'NR==1{print $3}'

Does the above command return lib, or lib64?

Because if lib64, phone cannot use 32 bit libs, which is what I have gathered is the reason why Repackaged refuses to install.

As an alternative, install AML and JamesDSP alongside V4A-RE to run both at the same time to get convolvers and such, since grayed out features are features V4A-RE doesn't yet support.

**Comment by 0izayoi0** [comment]
unfortunate, i found out its 64bit only a few days after commenting this sadly (nothing phone 2, something os 1.2) thanks for the alternative cant we get alternatives within the app? or atleast as a side project? thanks (like the alternative feature can stay until the feature is fully implemented, or maybe it could connect to james dsp)

**Comment by vjburic1** [comment]
Well what do you need exactly?

JamesDSP, along with Audio Modification Library Ryuki Mod, makes it possible to use both at the same time.

Convolvers? JDSP
Surround? Crossfeed in JDSP
Virtual room effect? JDSP too

And so on.

With AML you can run as many audio mods supported as you want - I managed to run Alpha Reverse Engineered, Repackaged (my phone supports 32 bit) and JDSP at the same time with it - 3 effects. Ofc, uninstalled Repackaged, don't need that many effects, just was curious.

But I'm not the dev, Iscle is. Or a programmer. Idk if that can be implemented actually. For now, use both apps and problem remedied.

**Comment by 0izayoi0** [comment]
just options that carries over from the jamesDSL app, only for the options to show up in the v4a app so its easier to control everything with 1 app

**Comment by vjburic1** [comment]
Yeah, I don't know that.

Different modules, two xml files mounted (same file, 2 apps), so it needs AML.

I guess this is needed:
It needs to access JamesDSP libs too I guess to access JDSP effects. Or redirect JDSP app UI to itself, somehow, or it's settings, so that changes are mirrored.

I really don't know. But personally? Not such an issue using 2 apps. Once you set them both how you want, no need to reopen them until you want to change it. JDSP recognizes different devices too with per-device profiles option activated.

**Comment by 0izayoi0** [comment]
i mean both works so ig ill use this, i hope progress on v4a re goes on well
